AUTO-75. Use build_lifecycle. Closes #64.

diff --git a/lib/templates/build_sh_app.erb b/lib/templates/build_sh_app.erb
--- a/lib/templates/build_sh_app.erb
+++ b/lib/templates/build_sh_app.erb
@@ -1,6 +1,9 @@
 #!/bin/sh
 SOURCE_DIR=`pwd`
 
+# Tell bash that we want the whole script to fail if any part fails.
+set -e
+
 #Begin
 echo "*************************************"
 echo "Running build script..."
